name: fz_all_apps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: 
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1 #Future<Either create good err handle
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  intl: ^0.17.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  go_router: 
  google_fonts: ^3.0.1
  # url_launcher: ^6.0.4

  get: ^4.6.1
  sqflite: ^2.0.2
  rflutter_alert: ^2.0.4
  flutter_typeahead: ^3.2.4 # اظهار ستاره بها بيانات اثناء الكتابه
  flutter_beep: ^1.0.0
  provider: ^6.0.2

  shared_preferences: ^2.0.13

  # pdf and path and open pubspec
  # create pdf
  pdf: ^3.6.1
  # save file
  path_provider: ^2.0.9
  # opne file
  open_file: ^3.2.1

  #restartApp
  restart_app: ^1.1.0

  #wave animation loading
  flutter_spinkit: ^5.1.0

  # syncfusion
  syncfusion_flutter_charts: ^20.1.50

  #Toast
  fluttertoast: ^8.0.8

  # #splash
  # animated_splash_screen: ^1.2.0

  # Qr Code
  qr_flutter: ^4.0.0
  # qr_code_scanner: ^0.7.0 #// got an error after flutter 3.

  # for printer
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.1.0


  # Use with the CupertinoIcons class for iOS style icons.
  month_picker_dialog: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    #icon launcher
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon_app.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf

  
  